// Company & product data — edit here, no database needed.

const COMPANY = {
  nameEn: "Pengxin Precision Plastics Co., Ltd.",
  nameZh: "深圳市鹏芯精密塑胶有限公司",
  nameTh: "บริษัท เผิงซิน พรีซิชั่น พลาสติกส์ จำกัด",
  founded: 2014,
  staff: 110,
  factoryArea: "3,200 m²",
  address: {
    en: "3F, Building B, Huafeng Technology Park, No. 3 Baotian 1st Road, Tiegang Community, Xixiang Street, Bao'an District, Shenzhen, China",
    zh: "深圳市宝安区西乡街道铁岗社区宝田一路3号华丰科技园B栋3楼",
    th: "ชั้น 3 อาคาร B สวนเทคโนโลยี Huafeng เลขที่ 3 ถนน Baotian 1 ตำบล Tiegang ถนน Xixiang เขต Bao'an เมืองเซินเจิ้น ประเทศจีน",
  },
  contact: {
    person: "Ms. Chen",
    whatsappDisplay: "+86 755 2300 0000",
    email: "sales@pengxin-mould.example",
    line: "pengxin_sales",
  },
};

const STATS = [
  { value: "2014", labelEn: "Established", labelZh: "成立年份", labelTh: "ก่อตั้ง" },
  { value: "110+", labelEn: "Staff", labelZh: "员工人数", labelTh: "พนักงาน" },
  { value: "18", labelEn: "Injection Machines", labelZh: "注塑机台数", labelTh: "เครื่องฉีดพลาสติก" },
  { value: "3,200 m²", labelEn: "Factory Area", labelZh: "厂房面积", labelTh: "พื้นที่โรงงาน" },
];

const PRODUCTS = [
  { sku: "PX-01", nameEn: "Clear TPU Airbag Case", nameZh: "透明气囊TPU壳", nameTh: "เคส TPU ใส", material: "TPU", spec: "Popular models",
    attrsEn: ["Air-cushion corners absorb drop impact", "Transparent, shows original phone color", "Precise cutouts for ports, buttons & camera"],
    attrsZh: ["四角气囊设计，缓冲跌落冲击", "透明款式，展现手机原色", "精准开孔，适配接口、按键与摄像头"],
    attrsTh: ["มุมกันกระแทกแบบแอร์แบ็ก ลดแรงกระแทกจากการตก", "ใสมองเห็นสีเครื่องเดิม", "เจาะช่องพอดีพอร์ต ปุ่มกด และกล้อง"],
    image: "images/PX-01.jpg" },
  { sku: "PX-02", nameEn: "Liquid Silicone Case", nameZh: "液态硅胶壳", nameTh: "เคสซิลิโคน", material: "Liquid Silicone", spec: "Multi-color, popular models",
    attrsEn: ["Soft-touch silicone exterior", "Microfiber-lined interior protects against scratches", "Slim, lightweight fit"],
    attrsZh: ["硅胶外壳，触感细腻", "内里植绒，防刮保护机身", "轻薄贴合"],
    attrsTh: ["ผิวซิลิโคนสัมผัสนุ่มลื่น", "ซับในไมโครไฟเบอร์ ป้องกันรอยขีดข่วน", "บางเบา กระชับพอดีเครื่อง"],
    image: "images/PX-02.jpg" },
  { sku: "PX-03", nameEn: "Card-Slot Case", nameZh: "插卡保护壳", nameTh: "เคสช่องบัตร", material: "PU + PC", spec: "Navy, popular models",
    attrsEn: ["Built-in card slot on the back", "PU leather texture with PC hard shell", "Slim profile despite added storage"],
    attrsZh: ["背部内置卡槽", "PU皮纹外观搭配PC硬壳", "带卡槽依然保持轻薄"],
    attrsTh: ["มีช่องใส่บัตรด้านหลัง", "พื้นผิวหนัง PU ผสานเปลือกแข็ง PC", "บางแม้จะมีช่องเก็บของ"],
    image: "images/PX-03.jpg" },
  { sku: "PX-04", nameEn: "Folding Desk Stand", nameZh: "折叠桌面支架", nameTh: "แท่นวางพับได้", material: "Aluminum + Silicone", spec: "Universal",
    attrsEn: ["Aluminum alloy frame with silicone anti-slip pads", "Adjustable multi-angle viewing", "Folds flat for portability"],
    attrsZh: ["铝合金支架，硅胶防滑垫", "多角度可调节", "可折叠便携收纳"],
    attrsTh: ["โครงอลูมิเนียมอัลลอยพร้อมแผ่นกันลื่นซิลิโคน", "ปรับมุมมองได้หลายระดับ", "พับเก็บพกพาสะดวก"],
    image: "images/PX-04.jpg" },
  { sku: "PX-05", nameEn: "2.5D Clear Tempered Glass", nameZh: "2.5D高清钢化膜", nameTh: "ฟิล์มกระจกใส", material: "9H Glass", spec: "Popular models",
    attrsEn: ["9H hardness resists scratches from keys & sand", "0.3mm thickness keeps touch sensitivity", "Oleophobic coating repels fingerprints"],
    attrsZh: ["9H硬度，抗钥匙沙粒刮擦", "0.3mm厚度，触控灵敏不受影响", "疏油涂层，减少指纹残留"],
    attrsTh: ["ความแข็ง 9H ทนรอยขีดข่วนจากกุญแจและทราย", "หนา 0.3มม. สัมผัสหน้าจอไวเหมือนเดิม", "เคลือบสารกันลายนิ้วมือ"],
    image: "images/PX-05.jpg" },
  { sku: "PX-06", nameEn: "Privacy Tempered Glass", nameZh: "防窥钢化膜", nameTh: "ฟิล์มกันสายตา", material: "Glass", spec: "Popular models",
    attrsEn: ["9H hardness anti-scratch glass", "Anti-peep filter blocks side-angle viewing", "Oleophobic coating repels fingerprints"],
    attrsZh: ["9H硬度耐刮玻璃", "防窥膜层，侧面视角无法看清屏幕", "疏油涂层，减少指纹"],
    attrsTh: ["กระจกแข็ง 9H ทนรอยขีดข่วน", "ชั้นกันสายตา มองจากด้านข้างไม่เห็นจอ", "เคลือบสารกันลายนิ้วมือ"],
    image: "images/PX-06.jpg" },
  { sku: "PX-07", nameEn: "Camera Lens Glass Set", nameZh: "镜头膜套装", nameTh: "ฟิล์มเลนส์", material: "Glass + Aluminum Ring", spec: "Universal set",
    attrsEn: ["Tempered glass with aluminum alloy ring frame", "Protects camera lens from scratches", "Easy peel-and-stick installation"],
    attrsZh: ["钢化玻璃配铝合金圈框", "保护摄像头镜头防刮花", "揭膜即贴，安装简单"],
    attrsTh: ["กระจกนิรภัยพร้อมขอบอลูมิเนียมอัลลอย", "ป้องกันเลนส์กล้องจากรอยขีดข่วน", "ติดตั้งง่าย ลอกแล้วแปะ"],
    image: "images/PX-07.jpg" },
  { sku: "PX-08", nameEn: "Wrist Strap", nameZh: "短款腕带", nameTh: "สายคล้องข้อมือ", material: "Nylon", spec: "Black / Beige",
    attrsEn: ["Adjustable nylon strap length", "Quick-release connector", "Prevents phone drops while walking"],
    attrsZh: ["尼龙材质，长度可调", "快拆式连接扣", "行走时有效防止手机跌落"],
    attrsTh: ["สายไนลอน ปรับความยาวได้", "หัวต่อแบบถอดเร็ว", "ป้องกันมือถือหล่นขณะเดิน"],
    image: "images/PX-08.jpg" },
  { sku: "PX-09", nameEn: "Vent Car Mount", nameZh: "出风口车载支架", nameTh: "ที่ยึดมือถือในรถ", material: "ABS", spec: "Non-wireless",
    attrsEn: ["Clips onto air-conditioning vent", "360° rotation for portrait or landscape view", "One-hand release button"],
    attrsZh: ["卡扣式固定于空调出风口", "360°旋转，横竖屏皆可", "单手按压即可取放"],
    attrsTh: ["หนีบติดกับช่องแอร์ในรถ", "หมุนได้ 360° ใช้ได้ทั้งแนวตั้งแนวนอน", "ปุ่มปลดล็อกใช้มือเดียว"],
    image: "images/PX-09.jpg" },
  { sku: "PX-10", nameEn: "Tempered Glass 10-Pack", nameZh: "钢化膜十片装", nameTh: "ชุดฟิล์ม 10 ชิ้น", material: "Glass", spec: "Bulk pack",
    attrsEn: ["9H hardness, 0.3mm thickness", "Bulk pack of 10 for retail resale", "Includes install kit (wipe + dust sticker)"],
    attrsZh: ["9H硬度，0.3mm厚度", "10片装，适合零售分装", "附安装套件（湿巾+除尘贴）"],
    attrsTh: ["ความแข็ง 9H หนา 0.3มม.", "แพ็ค 10 ชิ้น เหมาะสำหรับขายปลีก", "มีชุดติดตั้ง (ผ้าเช็ด+สติกเกอร์ดักฝุ่น)"],
    image: "images/PX-10.jpg" },
  { sku: "PX-11", nameEn: "Shockproof Clear Case", nameZh: "加厚防摔壳", nameTh: "เคสกันกระแทก", material: "TPU", spec: "Reinforced corners",
    attrsEn: ["Reinforced corner cushioning for drop protection", "Anti-yellowing TPU formula", "Transparent, shows original phone color"],
    attrsZh: ["四角加厚缓冲，防摔耐用", "TPU抗黄配方", "透明款式，展现手机原色"],
    attrsTh: ["มุมหนาพิเศษ ป้องกันการตกกระแทก", "สูตร TPU กันเหลือง", "ใสมองเห็นสีเครื่องเดิม"],
    image: "images/PX-11.jpg" },
  { sku: "PX-12", nameEn: "Flower Ring Holder", nameZh: "指环扣", nameTh: "แหวนมือถือ", material: "Zinc Alloy", spec: "Multi-color",
    attrsEn: ["360° rotating ring for secure grip", "Doubles as a kickstand", "Adhesive base, multiple colors"],
    attrsZh: ["360°旋转指环，握持更稳", "可当支架使用", "背胶粘贴，多色可选"],
    attrsTh: ["แหวนหมุนได้ 360° จับถนัดมือ", "ใช้เป็นขาตั้งได้ด้วย", "ฐานกาวติด มีหลายสีให้เลือก"],
    image: "images/PX-12.jpg" },
];
